version: "3.9"

services:
  react-app:
    build: .
    container_name: react-app
    ports:
      - "9000:9000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
